version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Backend"
    schedule:
      interval: "daily"
    groups:
      backend-minor:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/Frontend"
    schedule:
      interval: "daily"
    groups:
      frontend-minor:
        update-types: ["minor", "patch"]