version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Backend"
    schedule:
      interval: "daily"
    groups:
      backend-minor:
        update-types: ["minor", "patch", "security"]
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
    open-pull_request-limit: 10
    auto-merge: true

  - package-ecosystem: "npm"
    directory: "/Frontend"
    schedule:
      interval: "daily"
    groups:
      frontend-minor:
        update-types: ["minor", "patch", "security"]
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
    open-pull_request-limit: 10
    auto-merge: true