name: Dependabot-reviewer

on: pull_request_target

permissions:
    pull-requests: write
    contents: write

jobs:
    review-dependent-pr:
        runs-on: ubuntu-latest

        if: ${{github.actor == 'dependabot[bot]'}}
        steps:
          - name: Dependabot metadata
            id: dependabot-metadata
            uses: dependabot/fetch-metadata@v2     
            with:
                github-token: ${{secrets.GITHUB_TOKEN}}  
        
          - name: Debug metadata (logs)
            run: |
                echo "PR=#${{ github.event.pull_request.number}}" 
                echo "update-type=${{ steps.dependabot-metadata.outputs.update-type}}" 
                echo "dependency-names=${{ steps.dependabot-metadata.outputs.dependency-names}}"

          - name: Auto-approve patch/minor/security updates
            if: |
                contains(steps.dependabot-metadata.outputs.update-type, 'version-update:semver-patch') || 
                contains(steps.dependabot-metadata.outputs.update-type, 'version-update:semver-minor') || 
                contains(steps.dependabot-metadata.outputs.update-type, 'security')
            uses: hmarr/auto-approve-action@v2
            with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                review-message: "Auto-approved PR"

          - name: Enable auto-merge for auto-approved
            if: |
                contains(steps.dependabot-metadata.outputs.update-type, 'version-update:semver-patch') || 
                contains(steps.dependabot-metadata.outputs.update-type, 'security')
            uses: peter-evans/enable-pull-request-automerge@v2
            with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                pull-request-number: ${{ github.event.pull_request.number}}
                merge-method: squash
        
          - name: Label the major updates
            if: contains( steps.dependabot-metadata.outputs.update-type, 'version-update:semver-major')
            uses: actions-ecosystem/action-add-labels@v1
            with:
                github_token: ${{secrets.GITHUB_TOKEN}}
                labels: Major update